# Stage 1: Builder
FROM node:20 AS builder

WORKDIR /app

COPY package.json .
COPY app.js .

RUN npm install

# Stage 2: Minimal Image
FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app .

EXPOSE 4000

CMD ["node", "app.js"]